<?php
/** Site-wide service credentials. Group playback settings live in the frontend. */
if ( ! defined( 'ABSPATH' ) ) { exit; }
?>
<div class="ds-app-wrap ds-ops">
	<nav class="ds-ops-nav" aria-label="<?php esc_attr_e( 'Screens byKUTT administration', 'digital-signage' ); ?>"><a class="ds-ops-brand" href="<?php echo esc_url( admin_url( 'admin.php?page=digital-signage' ) ); ?>"><span class="ds-ops-mark"></span><strong>Screens <small>byKUTT</small></strong></a><div><a href="<?php echo esc_url( admin_url( 'admin.php?page=digital-signage' ) ); ?>"><?php esc_html_e( 'Overview', 'digital-signage' ); ?></a><a href="<?php echo esc_url( admin_url( 'admin.php?page=ds-guides' ) ); ?>"><?php esc_html_e( 'Guides', 'digital-signage' ); ?></a><a class="active" href="<?php echo esc_url( admin_url( 'admin.php?page=ds-settings' ) ); ?>"><?php esc_html_e( 'Global settings', 'digital-signage' ); ?></a></div><a class="ds-ops-button" href="<?php echo esc_url( DS_Portal::url( 'settings' ) ); ?>"><?php esc_html_e( 'Group settings', 'digital-signage' ); ?></a></nav>
	<header class="ds-ops-page-head"><p><?php esc_html_e( 'Global configuration', 'digital-signage' ); ?></p><h1><?php esc_html_e( 'Connect services once. Keep daily work in the frontend.', 'digital-signage' ); ?></h1><span><?php esc_html_e( 'Secrets are stored by WordPress and are never shown again after saving.', 'digital-signage' ); ?></span></header>
	<?php if ( isset( $_GET['spotify_saved'] ) || isset( $_GET['recaptcha_saved'] ) ) : ?><div class="ds-notice ds-notice-success"><?php esc_html_e( 'Global service settings saved.', 'digital-signage' ); ?></div><?php endif; ?>
	<section class="ds-global-grid">
		<article class="ds-global-card" id="spotify"><header><span class="ds-service-icon spotify">S</span><div><h2><?php esc_html_e( 'Spotify Web API', 'digital-signage' ); ?></h2><p><?php esc_html_e( 'Required for Web API search, playback controls, album artwork, and Web Playback SDK controller output.', 'digital-signage' ); ?></p></div></header><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="ds_save_spotify_settings"><?php wp_nonce_field( 'ds_save_spotify_settings' ); ?><label><?php esc_html_e( 'Client ID', 'digital-signage' ); ?><input name="client_id" value="<?php echo esc_attr( $spotify_settings['client_id'] ?? '' ); ?>" autocomplete="off"></label><label><?php esc_html_e( 'Client secret', 'digital-signage' ); ?><input type="password" name="client_secret" autocomplete="new-password" placeholder="<?php echo ! empty( $spotify_settings['client_secret'] ) ? esc_attr__( 'Saved — enter only to replace', 'digital-signage' ) : ''; ?>"></label><label><?php esc_html_e( 'Redirect URI', 'digital-signage' ); ?><div class="ds-copy-field"><input value="<?php echo esc_attr( DS_Spotify::redirect_uri() ); ?>" readonly><button type="button" data-copy="<?php echo esc_attr( DS_Spotify::redirect_uri() ); ?>"><?php esc_html_e( 'Copy', 'digital-signage' ); ?></button></div><small><?php esc_html_e( 'Add this exact URI in the Spotify Developer Dashboard.', 'digital-signage' ); ?></small></label><button class="ds-ops-button"><?php esc_html_e( 'Save Spotify settings', 'digital-signage' ); ?></button></form></article>
		<article class="ds-global-card" id="recaptcha"><header><span class="ds-service-icon captcha">✓</span><div><h2><?php esc_html_e( 'Google reCAPTCHA', 'digital-signage' ); ?></h2><p><?php esc_html_e( 'Optional reCAPTCHA v2 checkbox protection for the custom frontend login and registration forms.', 'digital-signage' ); ?></p></div></header><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="ds_save_recaptcha_settings"><?php wp_nonce_field( 'ds_save_recaptcha_settings' ); ?><label><?php esc_html_e( 'Site key', 'digital-signage' ); ?><input name="site_key" value="<?php echo esc_attr( $recaptcha_settings['site_key'] ?? '' ); ?>" autocomplete="off"></label><label><?php esc_html_e( 'Secret key', 'digital-signage' ); ?><input type="password" name="secret_key" autocomplete="new-password" placeholder="<?php echo ! empty( $recaptcha_settings['secret_key'] ) ? esc_attr__( 'Saved — enter only to replace', 'digital-signage' ) : ''; ?>"></label><small><?php esc_html_e( 'Leave either key empty to keep reCAPTCHA disabled. Verification is performed server-side before authentication.', 'digital-signage' ); ?></small><button class="ds-ops-button"><?php esc_html_e( 'Save reCAPTCHA settings', 'digital-signage' ); ?></button></form></article>
	</section>
	<aside class="ds-guide-note"><strong><?php esc_html_e( 'Group settings moved to Screen Manager.', 'digital-signage' ); ?></strong><p><?php esc_html_e( 'Channels, Screens, controllers, people, schedules, media, playback defaults, and group timezones are managed only from the frontend. This area contains site-wide operations and third-party service keys.', 'digital-signage' ); ?></p></aside>
</div>
