<?php
/** Frontend login and registration screen. */
if ( ! defined( 'ABSPATH' ) ) { exit; }
$is_login = 'login' === $mode;
$messages = array(
	'login_failed'    => __( 'The email or password is incorrect, or this account cannot manage screens.', 'digital-signage' ),
	'register_failed' => __( 'Check every field. Use a new email address and a password with at least 10 characters.', 'digital-signage' ),
	'rate_limited'    => __( 'Too many registration attempts. Please wait one hour and try again.', 'digital-signage' ),
);
?>
<!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo( 'charset' ); ?>"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo esc_html( $is_login ? __( 'Sign in — Screen Manager', 'digital-signage' ) : __( 'Create account — Screen Manager', 'digital-signage' ) ); ?></title><?php wp_head(); ?></head>
<body class="ds-auth-page"><main class="ds-auth-shell"><section class="ds-auth-intro"><a class="ds-auth-brand" href="<?php echo esc_url( home_url( '/' ) ); ?>"><span>DS</span><strong>Screen Manager</strong></a><div><h1><?php echo esc_html( $is_login ? __( 'Your screens, ready when you are.', 'digital-signage' ) : __( 'Start with one pairing code.', 'digital-signage' ) ); ?></h1><p><?php echo esc_html( $is_login ? __( 'Manage every linked display, channel and schedule from one quiet workspace.', 'digital-signage' ) : __( 'Create your workspace, then enter the six-character code shown on your signage computer.', 'digital-signage' ) ); ?></p></div><small><?php esc_html_e( 'screens.kutt.ee', 'digital-signage' ); ?></small></section><section class="ds-auth-form-wrap"><div class="ds-auth-form"><h2><?php echo esc_html( $is_login ? __( 'Sign in', 'digital-signage' ) : __( 'Create your account', 'digital-signage' ) ); ?></h2><p><?php echo esc_html( $is_login ? __( 'Use your email address or username.', 'digital-signage' ) : __( 'You will own the controllers and screens you pair.', 'digital-signage' ) ); ?></p><?php if ( isset( $messages[ $status ] ) ) : ?><div class="ds-auth-error" role="alert"><?php echo esc_html( $messages[ $status ] ); ?></div><?php endif; ?>
<?php if ( $is_login ) : ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'ds_front_login' ); ?><input type="hidden" name="action" value="ds_front_login"><input type="hidden" name="redirect_to" value="<?php echo esc_attr( $redirect_to ); ?>"><label><?php esc_html_e( 'Email or username', 'digital-signage' ); ?><input name="user_login" autocomplete="username" required autofocus></label><label><?php esc_html_e( 'Password', 'digital-signage' ); ?><input type="password" name="user_password" autocomplete="current-password" required></label><div class="ds-auth-options"><label><input type="checkbox" name="remember" value="1"> <?php esc_html_e( 'Keep me signed in', 'digital-signage' ); ?></label><a href="<?php echo esc_url( wp_lostpassword_url( self::login_url() ) ); ?>"><?php esc_html_e( 'Forgot password?', 'digital-signage' ); ?></a></div><button type="submit"><?php esc_html_e( 'Sign in', 'digital-signage' ); ?></button></form><p class="ds-auth-switch"><?php esc_html_e( 'New to Screen Manager?', 'digital-signage' ); ?> <a href="<?php echo esc_url( self::register_url() ); ?>"><?php esc_html_e( 'Create account', 'digital-signage' ); ?></a></p>
<?php else : ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'ds_front_register' ); ?><input type="hidden" name="action" value="ds_front_register"><label><?php esc_html_e( 'Your name', 'digital-signage' ); ?><input name="display_name" autocomplete="name" required autofocus></label><label><?php esc_html_e( 'Email', 'digital-signage' ); ?><input type="email" name="user_email" autocomplete="email" required></label><label><?php esc_html_e( 'Password', 'digital-signage' ); ?><input type="password" name="user_password" autocomplete="new-password" minlength="10" required><small><?php esc_html_e( 'At least 10 characters.', 'digital-signage' ); ?></small></label><label><?php esc_html_e( 'Confirm password', 'digital-signage' ); ?><input type="password" name="password_confirmation" autocomplete="new-password" minlength="10" required></label><label class="ds-honeypot" aria-hidden="true">Website<input name="website" tabindex="-1" autocomplete="off"></label><button type="submit"><?php esc_html_e( 'Create account and pair a screen', 'digital-signage' ); ?></button></form><p class="ds-auth-switch"><?php esc_html_e( 'Already have an account?', 'digital-signage' ); ?> <a href="<?php echo esc_url( self::login_url() ); ?>"><?php esc_html_e( 'Sign in', 'digital-signage' ); ?></a></p><?php endif; ?></div></section></main><?php wp_footer(); ?></body></html>
