<?php if ( ! defined( 'ABSPATH' ) ) { exit; }
$user = wp_get_current_user(); $nav = array( 'overview' => 'Overview', 'channels' => 'Channels', 'screens' => 'Screens', 'controllers' => 'Controllers', 'sharing' => 'People' );
$controller = ( 'controllers' === $section && $id && self::can_access_controller( $id ) ) ? DS_Controllers::get( $id ) : null;
?>
<!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo( 'charset' ); ?>"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php esc_html_e( 'Signage Manager', 'digital-signage' ); ?></title><?php wp_head(); ?></head>
<body class="ds-portal"><div class="ds-shell">
<aside class="ds-side"><a class="ds-brand" href="<?php echo esc_url( self::url() ); ?>"><span>DS</span><strong>Signage</strong></a><nav><?php foreach ( $nav as $key => $label ) : ?><a class="<?php echo $section === $key ? 'active' : ''; ?>" href="<?php echo esc_url( self::url( $key ) ); ?>"><?php echo esc_html( $label ); ?></a><?php endforeach; ?></nav><div class="ds-account"><small><?php echo esc_html( $user->user_email ); ?></small><a href="<?php echo esc_url( wp_logout_url( home_url() ) ); ?>">Sign out</a></div></aside>
<main><header class="ds-top"><div><p class="ds-eyebrow">Digital signage</p><h1><?php echo esc_html( $nav[ $section ] ?? 'Overview' ); ?></h1></div><span class="ds-live">Controller ready</span></header>
<?php if ( isset( $_GET['saved'] ) ) : ?><div class="ds-notice">Saved. The device will receive this on its next check-in.</div><?php endif; ?>
<?php if ( isset( $_GET['error'] ) ) : ?><div class="ds-notice error"><?php esc_html_e( 'That request could not be completed. Check the fields and try again.', 'digital-signage' ); ?></div><?php endif; ?>
<?php if ( 'overview' === $section ) : ?>
<section class="ds-hero"><div><p class="ds-kicker">Your network</p><h2>Every screen, without the clutter.</h2><p>See what is connected, move quickly, and leave the complexity in the background.</p></div><a class="ds-button dark" href="<?php echo esc_url( self::url( 'controllers' ) ); ?>">Open controllers</a></section>
<div class="ds-metrics"><article><strong><?php echo count( $screens ); ?></strong><span>Screens</span></article><article><strong><?php echo count( $channels ); ?></strong><span>Channels</span></article><article><strong><?php echo count( $controllers ); ?></strong><span>Controllers</span></article></div>
<?php elseif ( 'channels' === $section ) : ?><section class="ds-list"><h2>Channels</h2><?php foreach ( $channels as $item ) : ?><article><div><strong><?php echo esc_html( $item->post_title ); ?></strong><small><?php echo (int) count( (array) get_post_meta( $item->ID, 'ds_shared_user_ids', true ) ); ?> people</small></div><span class="ds-pill">Ready</span></article><?php endforeach; ?><?php if ( ! $channels ) : ?><p class="ds-empty">No channels assigned to you.</p><?php endif; ?></section>
<?php elseif ( 'screens' === $section ) : ?><section class="ds-list"><h2>Screens</h2><?php foreach ( $screens as $item ) : $channel_id = absint( get_post_meta( $item->ID, 'ds_channel_id', true ) ); ?><article><div><strong><?php echo esc_html( $item->post_title ); ?></strong><small><?php echo esc_html( $channel_id ? get_the_title( $channel_id ) : 'No channel assigned' ); ?></small></div><span class="ds-pill">Configured</span></article><?php endforeach; ?><?php if ( ! $screens ) : ?><p class="ds-empty">No screens assigned to you.</p><?php endif; ?></section>
<?php elseif ( 'controllers' === $section && ! $controller ) : ?><section class="ds-list"><h2>Controllers</h2><?php foreach ( $controllers as $item ) : ?><a class="ds-row" href="<?php echo esc_url( self::url( 'controllers', array( 'id' => $item->id ) ) ); ?>"><div><strong><?php echo esc_html( $item->name ?: $item->hostname ); ?></strong><small><?php echo esc_html( $item->hostname ); ?></small></div><span>Manage →</span></a><?php endforeach; ?><?php if ( ! $controllers ) : ?><p class="ds-empty">No controllers assigned to your screens.</p><?php endif; ?></section>
<?php elseif ( $controller ) : $schedule = json_decode( (string) $controller->power_schedule, true ) ?: array(); ?>
<a class="ds-back" href="<?php echo esc_url( self::url( 'controllers' ) ); ?>">← All controllers</a><section class="ds-device"><p class="ds-kicker">Ubuntu controller</p><h2><?php echo esc_html( $controller->name ?: $controller->hostname ); ?></h2><p><?php echo esc_html( $controller->hostname ); ?></p><div class="ds-actions"><?php foreach ( array( 'start_players' => 'Start screens', 'stop_players' => 'Show desktop', 'restart_players' => 'Restart Chrome', 'software_update' => 'Update software', 'reboot' => 'Reboot device' ) as $command => $label ) : ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'ds_portal_action' ); ?><input type="hidden" name="action" value="ds_portal_action"><input type="hidden" name="operation" value="controller_command"><input type="hidden" name="controller_id" value="<?php echo (int) $controller->id; ?>"><input type="hidden" name="command_type" value="<?php echo esc_attr( $command ); ?>"><button><?php echo esc_html( $label ); ?></button></form><?php endforeach; ?></div></section>
<div class="ds-grid"><form class="ds-card" method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'ds_portal_action' ); ?><input type="hidden" name="action" value="ds_portal_action"><input type="hidden" name="operation" value="save_sleep_schedule"><input type="hidden" name="controller_id" value="<?php echo (int) $controller->id; ?>"><h3>Sleep schedule</h3><p>Turns connected displays off; Ubuntu stays awake.</p><label class="ds-check"><input type="checkbox" name="enabled" value="1" <?php checked( ! empty( $schedule['enabled'] ) ); ?>> Enable schedule</label><div class="ds-fields"><label>On<input type="time" name="wake_time" value="<?php echo esc_attr( $schedule['wake_time'] ?? '07:00' ); ?>"></label><label>Off<input type="time" name="sleep_time" value="<?php echo esc_attr( $schedule['sleep_time'] ?? '22:00' ); ?>"></label></div><label>Timezone<input name="timezone" value="<?php echo esc_attr( $schedule['timezone'] ?? wp_timezone_string() ); ?>"></label><div class="ds-days"><?php foreach ( array( 'Sun','Mon','Tue','Wed','Thu','Fri','Sat' ) as $day => $label ) : ?><label><input type="checkbox" name="days[]" value="<?php echo $day; ?>" <?php checked( in_array( $day, $schedule['days'] ?? range( 0, 6 ), true ) ); ?>><?php echo esc_html( $label ); ?></label><?php endforeach; ?></div><button class="ds-button dark">Save schedule</button></form>
<form class="ds-card danger" method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'ds_portal_action' ); ?><input type="hidden" name="action" value="ds_portal_action"><input type="hidden" name="operation" value="switch_url"><input type="hidden" name="controller_id" value="<?php echo (int) $controller->id; ?>"><h3>Switch URL</h3><p>The controller will forget this site, reboot, then pair with the new WordPress site.</p><label>New WordPress URL<input type="url" name="new_site_url" placeholder="https://new-site.example" required></label><label>Type <strong><?php echo esc_html( wp_parse_url( home_url(), PHP_URL_HOST ) ); ?></strong> to verify<input name="verify_host" required></label><label class="ds-check"><input type="checkbox" name="confirm_switch" value="1" required> I understand this controller will leave this website.</label><button class="ds-button warning">Switch URL and reboot</button></form></div>
<?php elseif ( 'sharing' === $section ) : ?><section class="ds-list"><h2>People</h2><p class="ds-intro">Give an existing WordPress user access by email. Only owners can change access.</p><?php foreach ( array_merge( $channels, $screens ) as $item ) : if ( ! current_user_can( 'manage_options' ) && (int) $item->post_author !== get_current_user_id() ) { continue; } ?><article class="ds-share"><div><strong><?php echo esc_html( $item->post_title ); ?></strong><small><?php echo esc_html( 'ds_channel' === $item->post_type ? 'Channel' : 'Screen' ); ?></small></div><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><?php wp_nonce_field( 'ds_portal_action' ); ?><input type="hidden" name="action" value="ds_portal_action"><input type="hidden" name="operation" value="share"><input type="hidden" name="post_id" value="<?php echo (int) $item->ID; ?>"><input type="email" name="email" placeholder="person@example.com" required><select name="share_action"><option value="add">Add</option><option value="remove">Remove</option></select><button>Apply</button></form></article><?php endforeach; ?></section><?php endif; ?>
</main></div><?php wp_footer(); ?></body></html>
